### ISSUE TITLE
Add ability to issue pre-authorised tokens ("Personal Access Tokens")

### ISSUE THREAD

**Issue by rmccue** [WP-API/OAuth2#11]
To match most of the other services out there, it should be easy to issue yourself a token. These tokens should probably have no expiry.

* [ ] Add built-in dummy app to own PATs
* [ ] Add UI to issue yourself a pre-authorised token

**Comment by almirbi** [comment]
I am going to take this one. One question though, should we really have a dummy app for this, or maybe add a "Generate Access Token" button inside of each application screen itself?

**Comment by rmccue** [comment]
We don't necessarily need a dummy app, but having it makes the rest of the code consistent (since you can assume a client app is always set). That said, probably causes more trouble than it's worth, so we should avoid a dummy app.
