### ISSUE TITLE
Clients' status is draft by default

### ISSUE THREAD

**Issue by almirbi** [WP-API/OAuth2#33]
When you create a new application, its status is set to draft even after clicking Save Client. Using the Client ID from a client that is in draft mode will return invalid client ID.

It might be un-intuitive for the users to go back to the list of applications and click "Approve" from the menu that appears on hover in order to enable the app. Maybe we should add a checkbox inside of the Edit Application screen that says "Published" or something like that. Thoughts?

**Comment by almirbi** [comment]
Additionally, you can do the first step of OAuth2 and get the code even though the client is in draft. But when trying to get the access token via the REST API, it returns an error. This should be synced as well

**Comment by rmccue** [comment]
> Maybe we should add a checkbox inside of the Edit Application screen that says "Published" or something like that.

Makes sense; this will eventually need proper UX design, but for now, this should work 👍

> Additionally, you can do the first step of OAuth2 and get the code even though the client is in draft.

Definitely a bug.

**Comment by almirbi** [comment]
Bug fixed in #34, closing this
