### ISSUE TITLE
Getting the consumer from within a plugin.

### ISSUE THREAD

**Issue by kosso** [WP-API/OAuth2#57]
HI,
When using the older WP-API/OAuth1 plugin, to get the consumer from within my plugin, I could use `$consumer = WP_REST_OAuth1_Client::get( $id );` 

What is the equivalent for this newer WP-API/OAuth2 plugin? 

Thanks.

**Comment by rmccue** [comment]
You can use `$client = WP\OAuth2\get_client( $id )` for this.
